// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package workers

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockWorker creates a new instance of MockWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorker {
	mock := &MockWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorker is an autogenerated mock type for the Worker type
type MockWorker struct {
	mock.Mock
}

type MockWorker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorker) EXPECT() *MockWorker_Expecter {
	return &MockWorker_Expecter{mock: &_m.Mock}
}

// DoWork provides a mock function for the type MockWorker
func (_mock *MockWorker) DoWork() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DoWork")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockWorker_DoWork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoWork'
type MockWorker_DoWork_Call struct {
	*mock.Call
}

// DoWork is a helper method to define mock.On call
func (_e *MockWorker_Expecter) DoWork() *MockWorker_DoWork_Call {
	return &MockWorker_DoWork_Call{Call: _e.mock.On("DoWork")}
}

func (_c *MockWorker_DoWork_Call) Run(run func()) *MockWorker_DoWork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWorker_DoWork_Call) Return(s string) *MockWorker_DoWork_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockWorker_DoWork_Call) RunAndReturn(run func() string) *MockWorker_DoWork_Call {
	_c.Call.Return(run)
	return _c
}
